<%
db_host    = ENV.fetch('DB_HOST', ENV.fetch('ITALIAAUTO_DB_1_PORT_5432_TCP_ADDR', 'localhost'))
db_port    = ENV['ITALIAAUTO_DB_1_PORT_5432_TCP_PORT'] || ENV['DB_PORT'] || 5432
require 'etc'
pool_size =
  # Web: max workers * max threads
  ENV.fetch('WEB_CONCURRENCY', 3).to_i * ENV.fetch('MAX_THREADS', 5).to_i +
  # ActiveJob Async max thread pool size
  Etc.nprocessors
ERB
%>

defaults: &defaults
  adapter: postgresql
  min_messages: WARNING
  pool: <%= pool_size %>
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= ENV.fetch('DB_USERNAME', 'italiaauto_dev').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', "italiaauto").inspect %>
  encoding: utf8

development:
  <<: *defaults
  database: italiaauto_dev
  username: postgres
  password: maximum8

test:
  <<: *defaults
  database: italiaauto_test


production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  database: italiaauto_production
  username: <%= Rails.application.credentials.db_prod_user %>
  password: <%= Rails.application.credentials.db_prod_pass %>
